[package]
name = "fst-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fst = { version = "0.4", features = ["levenshtein"] }
memmap = "0.7.0"
