[package]
name = "macro_demo"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macro_demo_trait = { path = "../macro_demo_trait" }
quote = "1.0"
syn = "1.0"