[package]
name = "libp2p_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.12.0"
env_logger = "0.9.0"
libp2p = "0.46.1"
log = "0.4.17"
