[package]
name = "sonic-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sonic-channel = { version = "1.1", features = ["ingest"] }

