[package]
name = "pprof-rs-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# pprof = "0.10.1"
pprof = { version = "0.10", features = ["flamegraph", "protobuf-codec"] }
